apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080

